# Generated by Django 6.0.7 on 2026-08-20 10:10

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_tbl_booking_zip_code'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_chat_message',
            name='booking_id',
            field=models.ForeignKey(blank=True, db_column='booking_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='booking.tbl_booking'),
        ),
        migrations.AddField(
            model_name='tbl_chat_message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbl_chat_message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tbl_chat_message',
            name='message_payload',
            field=chat.models.EncryptedTextField(max_length=500),
        ),
    ]
