# Generated by Django 6.0.7 on 2026-08-20 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_tbl_booking_zip_code'),
        ('chat', '0002_tbl_chat_message_booking_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tbl_chat_message',
            constraint=models.CheckConstraint(condition=models.Q(('sender_id', models.F('receiver_id')), _negated=True), name='sender_cannot_be_receiver'),
        ),
    ]
