# Generated by Django 6.0.7 on 2026-08-20 10:55

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_tbl_booking_zip_code'),
        ('chat', '0003_tbl_chat_message_sender_cannot_be_receiver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tbl_chat_message',
            constraint=models.CheckConstraint(condition=django.db.models.expressions.RawSQL('length(trim(message_payload)) > 0', [], output_field=models.BooleanField()), name='message_payload_not_empty_or_whitespace'),
        ),
    ]
