# Generated by Django 6.0.7 on 2026-09-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_tbl_user_profile_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user_profile',
            name='resume_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last resume upload', null=True),
        ),
        migrations.AddField(
            model_name='tbl_user_profile',
            name='resume_url',
            field=models.CharField(blank=True, help_text='Cloudinary public_id of the uploaded PDF resume', max_length=500, null=True),
        ),
    ]
