# Generated by Django 6.0.7 on 2026-09-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_resume_fields'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS organized_user_profiles CASCADE;",
            reverse_sql="",
        ),
        migrations.RemoveConstraint(
            model_name='tbl_user_profile',
            name='valid_verification_status_enum',
        ),
        migrations.RemoveField(
            model_name='tbl_user_profile',
            name='verification_status',
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW organized_user_profiles AS
            SELECT id, first_name, middle_name, last_name, account_type,
                   profile_link, email, contact_number, username, password,
                   gender, date_of_birth, nationality, religion, language,
                   street, city, province, zipcode, country,
                   is_active, is_staff, is_superuser, last_login, date_joined
            FROM accounts_tbl_user_profile;
            """,
            reverse_sql="DROP VIEW IF EXISTS organized_user_profiles;",
        ),
    ]

