# Generated by Django 6.0.7 on 2026-10-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_tbl_user_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user_profile',
            name='cancellation_strikes',
            field=models.PositiveIntegerField(default=0, help_text='Number of confirmed booking cancellations initiated by this user. 3 strikes lead to account restriction.'),
        ),
        migrations.AddField(
            model_name='tbl_user_profile',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text="Designates whether the user's booking/posting privileges are restricted due to policy violations or 3 cancellation strikes."),
        ),
    ]
