# Generated by Django 6.0.7 on 2026-10-07 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_tbl_booking_service_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='cancel_requested_by',
            field=models.ForeignKey(blank=True, db_column='cancel_requested_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancel_requested_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, db_column='cancelled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
