# Generated by Django 6.0.7 on 2026-08-24 10:02

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_tbl_booking_zip_code'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tbl_review',
            name='valid_review_direction_enum',
        ),
        migrations.AddField(
            model_name='tbl_review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_review',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_review',
            name='nlp_sentiment',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], default='Neutral', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_review',
            name='unstructured_feedback',
            field=models.TextField(default='No feedback', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tbl_review',
            constraint=models.UniqueConstraint(fields=('booking_id', 'reviewer_id'), name='one_review_per_user_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='tbl_review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='valid_rating_range_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='tbl_review',
            constraint=models.CheckConstraint(condition=models.Q(('reviewer_id', models.F('reviewee_id')), _negated=True), name='reviewer_cannot_be_reviewee'),
        ),
        migrations.RemoveField(
            model_name='tbl_review',
            name='review_direction',
        ),
    ]
