# Generated by Django 6.0.7 on 2026-09-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0003_alter_tbl_documents_date_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_documents',
            name='extracted_data',
            field=models.JSONField(blank=True, help_text='Structured data extracted by Groq AI from OCR text', null=True),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='ocr_discrepancies',
            field=models.JSONField(blank=True, default=list, help_text='List of field mismatches between OCR output and profile data'),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='ocr_match_score',
            field=models.FloatField(blank=True, help_text='0.0-1.0 score indicating how well OCR data matches profile', null=True),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='ocr_processed_at',
            field=models.DateTimeField(blank=True, help_text='When OCR + AI processing completed', null=True),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='ocr_raw_text',
            field=models.TextField(blank=True, help_text='Raw text extracted by OCR engine', null=True),
        ),
        migrations.AddField(
            model_name='tbl_documents',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for document rejection by Admin/Barangay', null=True),
        ),
        migrations.AlterField(
            model_name='tbl_documents',
            name='verification_status',
            field=models.CharField(choices=[('Unverified', 'Unverified'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
